// Service data for Mass Claim Center
// Move this to a shared location for reuse in dynamic pages

export const services = [
   {
      id: 1,
      slug: "depo-provera-lawsuits",
      title: "Depo-Provera Lawsuits",
      image: "/services/depo.png",
      icon: "💉",
      iconBg: "#e0f2f1",
      iconColor: "#ffffff",
      description:
         "Lawsuits alleging Depo-Provera caused brain tumors or other severe health issues.",
      cases: [
         "Brain tumor from Depo-Provera use",
         "Failure to warn about tumor risks",
         "Product liability for unsafe contraceptives",
         "Wrongful death from complications",
         "Health monitoring for long-term users",
      ],
   },
   {
      id: 2,
      slug: "roundup-weedkiller-lawsuits",
      title: "Roundup Weedkiller Lawsuits",
      image: "/services/round-up.png",
      icon: "🌿",
      iconBg: "#f1f8e9",
      iconColor: "#ffffff",
      description:
         "Lawsuits against Monsanto, claiming Roundup’s glyphosate caused cancers like non-Hodgkin’s lymphoma.",
      cases: [
         "Non-Hodgkin’s lymphoma from glyphosate",
         "Failure to warn about cancer risks",
         "Agricultural worker cancer claims",
         "Environmental exposure lawsuits",
         "Wrongful death from cancer",
      ],
   },
   {
      id: 3,
      slug: "talcum-powder-lawsuits",
      title: "Talcum Powder Lawsuits",
      image: "/services/talcum.png",
      icon: "🧴",
      iconBg: "#e3f2fd",
      iconColor: "#ffffff",
      description:
         "Claims against talcum powder manufacturers, alleging asbestos contamination caused ovarian cancer or mesothelioma.",
      cases: [
         "Ovarian cancer from talc use",
         "Mesothelioma due to asbestos",
         "Product liability for unsafe talc",
         "Failure to warn about asbestos risks",
         "Wrongful death from cancer",
      ],
   },
   {
      id: 4,
      slug: "necrotizing-enterocolitis-nec-lawsuits",
      title: "Necrotizing Enterocolitis (NEC) Lawsuits",
      image: "/services/nec.png",
      icon: "🍼",
      iconBg: "#f3e5f5",
      iconColor: "#ffffff",
      description:
         "Lawsuits against baby formula manufacturers, claiming formulas caused necrotizing enterocolitis in premature infants.",
      cases: [
         "Product liability for harmful formula",
         "Failure to warn about NEC risks",
         "Wrongful death from infant fatalities",
         "Medical expense claims for NICU care",
         "Negligence in formula marketing",
      ],
   },
   {
      id: 5,
      slug: "lds-church-lawsuits",
      title: "LDS Church Lawsuits",
      image: "/services/lds.png",
      icon: "⛪",
      iconBg: "#e0f2f1",
      iconColor: "#ffffff",
      description:
         "Legal actions against the LDS Church, often involving sexual abuse cover-ups or financial misconduct.",
      cases: [
         "Clergy sexual abuse claims",
         "Institutional cover-up of abuse",
         "Financial fraud in tithing practices",
         "Child protection policy violations",
         "Emotional distress from abuse handling",
      ],
   },
   {
      id: 6,
      slug: "rideshare-accidents",
      title: "Rideshare Accidents",
      image: "/services/rideshare.png",
      icon: "🚗",
      iconBg: "#ffebee",
      iconColor: "#ffffff",
      description:
         "Claims involving rideshare services like Uber or Lyft for accidents, injuries, or company negligence.",
      cases: [
         "Passenger injury from driver negligence",
         "Pedestrian accidents involving rideshare vehicles",
         "Third-party collision claims",
         "Company liability for poor driver screening",
         "Wrongful death in rideshare crashes",
      ],
   },
   {
      id: 7,
      slug: "paraquat-herbicide-lawsuits",
      title: "Paraquat Herbicide Lawsuits",
      image: "/services/paraquat.png",
      icon: "🌾",
      iconBg: "#fff3e0",
      iconColor: "#ffffff",
      description:
         "Lawsuits linking Paraquat exposure to Parkinson’s disease, targeting manufacturers for inadequate warnings.",
      cases: [
         "Parkinson’s disease from herbicide exposure",
         "Failure to disclose health risks",
         "Wrongful death from Paraquat illness",
         "Agricultural worker injury claims",
         "Environmental exposure lawsuits",
      ],
   },
   {
      id: 8,
      slug: "video-game-addiction-lawsuits",
      title: "Video Game Addiction Lawsuits",
      image: "/services/video-game.png",
      icon: "🎮",
      iconBg: "#fce4ec",
      iconColor: "#ffffff",
      description:
         "Claims against gaming companies for addictive game designs causing psychological or financial harm.",
      cases: [
         "Mental health damages from addiction",
         "Negligence in addictive game mechanics",
         "Underage spending on in-game purchases",
         "Loss of productivity lawsuits",
         "Parental claims for child neglect",
      ],
   },
   {
      id: 9,
      slug: "tylenol-acetaminophen-lawsuits",
      title: "Tylenol (Acetaminophen) Lawsuits",
      image: "/services/tylenol.png",
      icon: "💊",
      iconBg: "#ffebee",
      iconColor: "#ffffff",
      description:
         "Lawsuits claiming Tylenol use during pregnancy caused autism or ADHD in children.",
      cases: [
         "Autism linked to prenatal Tylenol use",
         "ADHD from acetaminophen exposure",
         "Failure to warn about developmental risks",
         "Product liability for unsafe labeling",
         "Medical expense claims for child care",
      ],
   },
   {
      id: 10,
      slug: "car-accident-lawsuits",
      title: "Car Accident Lawsuits",
      image: "/services/car-accident.png",
      icon: "🚘",
      iconBg: "#f3e5f5",
      iconColor: "#ffffff",
      description:
         "Legal claims for injuries or damages from car accidents, targeting negligent drivers or manufacturers.",
      cases: [
         "Personal injury from reckless driving",
         "Wrongful death in car crashes",
         "Vehicle defect liability",
         "DUI-related accident claims",
         "Pedestrian injury lawsuits",
      ],
   },
   {
      id: 11,
      slug: "zantac-lawsuits",
      title: "Zantac Lawsuits",
      image: "/services/zantac.png",
      icon: "💊",
      iconBg: "#e8f5e9",
      iconColor: "#ffffff",
      description:
         "Lawsuits claiming Zantac’s ranitidine caused cancers due to NDMA contamination.",
      cases: [
         "Cancer from NDMA exposure",
         "Failure to warn about contamination",
         "Product liability for defective drugs",
         "Wrongful death from cancer",
         "Health monitoring for exposed users",
      ],
   },
   {
      id: 12,
      slug: "ozempic-lawsuits",
      title: "Ozempic Lawsuits",
      image: "/services/ozempic.png",
      icon: "💉",
      iconBg: "#fff3e0",
      iconColor: "#ffffff",
      description:
         "Claims against Ozempic manufacturers for severe side effects like gastroparesis or gallbladder issues.",
      cases: [
         "Gastroparesis from Ozempic use",
         "Gallbladder injury claims",
         "Failure to warn about side effects",
         "Product liability for unsafe drugs",
         "Medical expense lawsuits",
      ],
   },
   {
      id: 13,
      slug: "hair-relaxer-lawsuits",
      title: "Hair Relaxer Lawsuits",
      image: "/services/hair-relaxer.png",
      icon: "💇‍♀️",
      iconBg: "#e0f7fa",
      iconColor: "#ffffff",
      description:
         "Lawsuits against hair relaxer manufacturers, alleging toxic chemicals caused cancers like uterine or ovarian cancer.",
      cases: [
         "Personal injury from uterine cancer",
         "Ovarian cancer due to chemical exposure",
         "Failure to warn about toxic ingredients",
         "Product liability for defective relaxers",
         "Wrongful death from cancer-related complications",
      ],
   },
   {
      id: 14,
      slug: "mesothelioma-lawsuits",
      title: "Mesothelioma Lawsuits",
      image: "/services/mesothelioma.png",
      icon: "⚖️",
      iconBg: "#fce4ec",
      iconColor: "#ffffff",
      description:
         "Claims against companies for asbestos exposure causing mesothelioma, a rare cancer.",
      cases: [
         "Mesothelioma from workplace asbestos",
         "Environmental asbestos exposure",
         "Failure to provide safety warnings",
         "Wrongful death from mesothelioma",
         "Product liability for asbestos products",
      ],
   },
   {
      id: 15,
      slug: "los-angeles-wildfire-lawsuits",
      title: "Los Angeles Wildfire Lawsuits",
      image: "/services/wildfire.png",
      icon: "🔥",
      iconBg: "#f1f8e9",
      iconColor: "#ffffff",
      description:
         "Lawsuits against utilities or entities for wildfires in LA causing property damage or injuries.",
      cases: [
         "Property damage from wildfires",
         "Personal injury from fire exposure",
         "Negligence in utility maintenance",
         "Wrongful death in wildfires",
         "Environmental damage claims",
      ],
   },
];
